<?php namespace App\Libraries;

use App\Units\BaseUnit;

/**
 * Class Outcome
 *
 * Results of an Action.
 */
class Outcome
{
	/**
	 * Timestamp from when the action completed.
	 *
	 * @var float
	 */
	public $timestamp;

	/**
	 * The unit that performed the action.
	 *
	 * @var BaseUnit
	 */
	public $unit;

	/**
	 * The results of the action.
	 *
	 * @var mixed
	 */
	public $data;

	/**
	 * Whether this outcome believes it should be recorded.
	 *
	 * @var bool
	 */
	public $keep;

	/**
	 * Save the parameters.
	 *
	 * @param float $timestamp  Timestamp from when the action complete
	 * @param BaseUnit $unit    The unit that issued the action
	 * @param mixed $data       The data generated by the action
	 * @param bool|null $keep   Whether this outcome believes it should be recorded
	 */
	public function __construct(float $timestamp, BaseUnit &$unit, $data, $keep = null)
	{
		$this->timestamp = $timestamp;
		$this->unit      = $unit;
		$this->data      = $data;
		
		// If $keep wasn't specified then check for data that seems relevent
		if ($keep === null && ! is_bool($data))
		{
			$this->keep = true;
		}
	}
}
