<?php namespace App\Libraries;

use App\Units\Unit;

/**
 * Class Outcome
 *
 * Results of an Action.
 */
class Outcome
{
	/**
	 * Timestamp from when the action completed.
	 *
	 * @var float
	 */
	public $timestamp;

	/**
	 * The unit that performed the action.
	 *
	 * @var Unit
	 */
	public $unit;

	/**
	 * The results of the action.
	 *
	 * @var array
	 */
	public $data;

	/**
	 * Save the parameters.
	 *
	 * @param float $timestamp  Timestamp from when the action complete
	 * @param Unit $unit        The unit that issued the action
	 * @param array $data       The data generated by the action
	 */
	public function __construct(float $timestamp, Unit &$unit, array $data)
	{
		$this->timestamp = $timestamp;
		$this->unit      = $unit;
		$this->data      = $data;
	}
}
